# Generated by Django 3.1 on 2020-10-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_auto_20201010_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumemodel',
            name='profilepicture',
            field=models.ImageField(default='noname', upload_to='images'),
            preserve_default=False,
        ),
    ]
