# Generated by Django 3.1 on 2020-10-10 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_resumemodel_profilepicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumemodel',
            name='profilepicture',
        ),
    ]
