# Generated by Django 3.1 on 2020-10-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_remove_resumemodel_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumemodel',
            name='profilepicture',
            field=models.ImageField(default='nonmae', upload_to='images'),
            preserve_default=False,
        ),
    ]
