# Generated by Django 3.1 on 2020-10-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_resumemodel_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumemodel',
            name='dob',
            field=models.CharField(max_length=20),
        ),
    ]
