# Generated by Django 3.1 on 2020-10-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_auto_20201010_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumemodel',
            name='lastdegree',
            field=models.CharField(choices=[('10', '10'), ('+2', '+2'), ('Diploma', 'Diploma'), ('Degree', 'Degree'), ('P.G', 'P.G'), ('B.Tech', 'B.Tech'), ('M.Tech', 'M.tech')], max_length=50),
        ),
    ]
